import { Geist, Geist_Mono } from "next/font/google";
import BreadCrumbComponent from "@/components/BreadCrumbComponent";
import { UserProvider } from "@/components/user-context";

// export const metadata: Metadata = {
//   title: "Shadcn Dashboard App",
//   description: "Generated by create next app",
// };

export default async function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <BreadCrumbComponent />
      <UserProvider>{children}</UserProvider>
    </div>
  );
}
